### PR TITLE
Updating multi_json, & stringext dependencies to be more modern.

### PR DESCRIPTION
**Pull request by nmccready**
updating dependencies for multi_json, and stringsext. All specs pass. This is a must for locomotivecms compatibility.

### CODE REVIEW

**Comment by tpitale** [comment]
@nmccready If you could update this against master, I will try to get it merged for 1.3.0.

**Comment by nmccready** [comment]
I'll pull it down and merge, hopefully it still works. I haven't touched this stuff in forever.

**Comment by tpitale** [comment]
@nmccready Thanks! I know this is been dead for a long time. Trying to tackle a little at a time. Appreciate you taking a look.

**Comment by nmccready** [comment]
merged

**Comment by nmccready** [comment]
You might want to add a .travis.yml file to test in the cloud

**Comment by nmccready** [comment]
Do I need to drop the versions down any on stringex?

**Comment by tpitale** [comment]
Thanks! Yeah, getting all the projects on Travis is one of my tasks. We have inconsistent coverage there. :smile:

I think the version of `stringex` is fine for now. Latest is 2.6.0, so folks can upgrade if they'd like to.

**Pull request merged**
